### ISSUE TITLE
No longer shows track inline stuff (ISRC, AcoustID, tools)

### ISSUE THREAD

**Issue by redactedscribe** [jesus2099/konami-command#682]
The script would previously show AcoustIDs next to each track's name, however this has stopped working. Perhaps the script is broken in other ways, but this is all I've noticed so far.

Thanks.

`@version 2021.6.21`

**Comment by jesus2099** [comment]
It works for me…?
Ah, it's in beta.musicbrainz.org, only! right?

So it would be because of one of these current in beta tickets:

- New Feature [Allow filtering events](https://tickets.metabrainz.org/browse/MBS-12212)
- New Feature [report for "digital releases with non-digital relationships"](https://tickets.metabrainz.org/browse/MBS-12385)
- New Feature [Add tobarandualchais.co.uk to the other dbs whitelist (and as free streaming for recordings)](https://tickets.metabrainz.org/browse/MBS-12407)
- Improvement [Improve error handling when checking donation status](https://tickets.metabrainz.org/browse/MBS-4960)
- Improvement [Cleanup /intent/user Twitter URLs](https://tickets.metabrainz.org/browse/MBS-11694)
- Improvement [Block smart links: share.amuse.io](https://tickets.metabrainz.org/browse/MBS-12333)
- Improvement [Allow navigation from donation check page](https://tickets.metabrainz.org/browse/MBS-12361)
- Improvement [Add title to pencil editing buttons in the external links editor](https://tickets.metabrainz.org/browse/MBS-12387)
- Bug [Long words in edit notes etc. break layout](https://tickets.metabrainz.org/browse/MBS-8193)
- Bug [Report "CatNoLooksLikeASIN" is equivalent to the North American catalog of the Universal Music Group](https://tickets.metabrainz.org/browse/MBS-8875)
- Bug [Cover art gallery dialog activated twice on some pages ](https://tickets.metabrainz.org/browse/MBS-12328)
- Bug [interface breaks with loong titles](https://tickets.metabrainz.org/browse/MBS-12332)
- Bug [Ensure Predicate::Set is passed the right thing before passing it to the DB](https://tickets.metabrainz.org/browse/MBS-12336)
- Bug [Release group artist not displayed in inline search if type empty](https://tickets.metabrainz.org/browse/MBS-12347)
- Bug [ISE when trying to enter disallowed value for ratings](https://tickets.metabrainz.org/browse/MBS-12353)
- Bug [webservice returns old (wrong) ASIN after edit that changes ASIN](https://tickets.metabrainz.org/browse/MBS-12398)
- Bug [Fail gracefully if requesting an invalid ID in edit-cover-art](https://tickets.metabrainz.org/browse/MBS-12412)
- Bug [ISE when requesting doc page with â€œ in URL](https://tickets.metabrainz.org/browse/MBS-12413)

**Comment by jesus2099** [comment]
It's not only AcoustID.

So for a beta 10 track release, INLINE STUFF is throws:

```
react-dom.production.min.js:118 Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Gr (react-dom.production.min.js:118:466)
    at gs (react-dom.production.min.js:199:369)
    at gu (react-dom.production.min.js:280:85)
    at mu (react-dom.production.min.js:279:450)
    at hu (react-dom.production.min.js:279:320)
    at pu (react-dom.production.min.js:279:180)
    at eu (react-dom.production.min.js:267:209)
    at x (scheduler.production.min.js:13:203)
    at MessagePort.O (scheduler.production.min.js:14:128)
```

Then 10:

```
react-dom.production.min.js:147 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Lo (react-dom.production.min.js:147:278)
    at vl (react-dom.production.min.js:292:486)
    at mu (react-dom.production.min.js:279:389)
    at hu (react-dom.production.min.js:279:320)
    at pu (react-dom.production.min.js:279:180)
    at eu (react-dom.production.min.js:267:209)
    at x (scheduler.production.min.js:13:203)
    at MessagePort.O (scheduler.production.min.js:14:128)
```

Then:

```
react-dom.production.min.js:292 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at vl (react-dom.production.min.js:292:155)
    at mu (react-dom.production.min.js:279:389)
    at hu (react-dom.production.min.js:279:320)
    at pu (react-dom.production.min.js:279:180)
    at tu (react-dom.production.min.js:270:88)
    at eu (react-dom.production.min.js:267:429)
    at x (scheduler.production.min.js:13:203)
    at MessagePort.O (scheduler.production.min.js:14:128)
```

**Comment by jesus2099** [comment]
Strange, I don't see anything related to tracklists in the [tickets available for beta testing](https://tickets.metabrainz.org/issues/?filter=10715), specifically in the current [18 tickets copied in my earlier comment](https://github.com/jesus2099/konami-command/issues/682#issuecomment-1143629896), for the record (any later ticket will be even less related).

**Comment by jesus2099** [comment]
It looks like React was updated on beta and that, maybe, **this new React would completely prevent any userscripts trying to modify a React hydrated area!?**

**Comment by jesus2099** [comment]
The problem may come from: **_StrictMode** has been enabled on all hydrated elements_
It sounds… _**strict**_.

**Comment by mwiencek** [comment]
I opened https://github.com/metabrainz/musicbrainz-server/pull/2559 which I hope will help, but it doesn't seem to fix the hydration errors. (I modified the INLINE STUFF script to run on my local dev server to check it against that patch.) It seems the user script is still running before hydration occurs (which happens inside a [jQuery ready handler](https://learn.jquery.com/using-jquery-core/document-ready/).)

**Comment by jesus2099** [comment]
Thank you very much for giving some time here, @mwiencek!

Thanks to your explanation, I completely understand what happens and what to do now, it should be easy!

Notice that the set comment script still works, because it is **launched later** (document-idle instead of document-ready) and then [**delayed even further** by one second.](https://github.com/murdos/musicbrainz-userscripts/commit/41b34e57df4093d2c2e1e1eb4e0928846384a561).

**Comment by jesus2099** [comment]
Sorry to make you lose time, @mwiencek!
Don't worry, I will take care of this.

In fact I already had this bug before (unsolved #596), it's just that now, the React hydrate takes longer so it triggers more often (systematically)

I will fix this by finally writing a new version that handles all kinds **paginated releases** (#38), like recently done for COLLECTION HIGHLIGHTER.

**It will solve this issue at the same time!**

Thanks again for your bug report, @redactedscribe!

Closing this as **duplicate of #596.**

**Comment by jesus2099** [comment]
I reopen because I had troubles finding this back.

**Comment by jesus2099** [comment]
**Workaround is to make this script near or at the end of your userscript list.**

Thanks for your report! and tell me if the workaround doesn't work for you.

**Comment by redactedscribe** [comment]
> Thanks for your report! and tell me if the workaround doesn't work for you.

Unfortunately it doesn't work. I'm on non-beta, moved INLINE to the bottom of the scripts list, disabled all scripts but INLINE for a particular release page, reloaded (re-cached) the page, still no ISRCs (they're not toggled hidden either).

**Comment by jesus2099** [comment]
You need some scripts to run before for the workaround to work.
The aim is to delay the run of INLINE script after many slow scripts. 😉
I did not change anything in my userscript list and it works for me (Android 9, Kiwi Browser, Violentmonkey), it's in the middle of the list.

**Comment by redactedscribe** [comment]
Even with all my scripts enabled and INLINE and the bottom, I still don't see any AcoustIDs next to the release tracks. I guess I'll just have to wait until you have time and find a fix. Thanks though.

**Comment by jesus2099** [comment]
Please tell in #596 if the quick fix worked for you. :)
